### ISSUE TITLE
Bundle() not resolving all $ref

### ISSUE THREAD

**Issue by uonze** [APIDevTools/swagger-parser#161]
When referencing the same component from other different components, Bundle() won't resolve the references correctly.

In this example:
![ApiReferences](https://kroki.io/mermaid/svg/eNpLL0osyFDwCeJSUHCMdgzwjFXQ1bVTcAJynaJDi1OLnPPzSlIrSiDCLiBhMMsZyHKJdiwuzk_OTCzJzM-DqQOKO4M1hiXmlKYWw_QBANrGHbU=)

The bundled output contains a external reference in UserValues to AssociationContext:
```
components:
  schemas:
    User.Context:
      type: object
      properties:
        values:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: Universal unique identifier of product property value.
                format: uuid
                example: dae18b3a-c5fc-4dc3-a53e-64c905d1f97b
              associationContext:
                type: array
                items:
                  $ref: >-
                    #/components/schemas/User.Context/properties/associationContext/items
```

**API Samples:**
[API](https://gist.github.com/uonze/b2ed893dd254a9aca6855b18dfb6b968)
[UserContext](https://gist.github.com/uonze/f5848f8f7139fbff56219844b9b6bf85)
[UserValues](https://gist.github.com/uonze/0c8ff7d19831b56352168e22dd74142e)
[AssociationContext](https://gist.github.com/uonze/d9efd7a8b148af59be226e4ce3e3d936)

**Results**
[Obtained](https://gist.github.com/uonze/168610fa4851e03ab4bfb9fd2d988b09)
[Expected](https://gist.github.com/uonze/23d1b52b0e064a8549b6a7712bce914f)

By changing UserValues to reference a duplicate of AssociationContext (New.AssociationContext) the Bundle() works correctly.
![ApiReferencesWorkaround](https://kroki.io/mermaid/svg/eNpLL0osyFDwCeJSUHCMdgzwjFXQ1bVTcAJynaJDi1OLnPPzSlIrSiDCLiBhMMsZyHKJdiwuzk_OTCzJzM-DqQOKO4M1hiXmlKYWQ_S5AkVdkUSx6QMApGYqbg==)
