### ISSUE TITLE
Deep references to external schemes are incorrectly resolved 

### ISSUE THREAD

**Issue by isadovskiy** [APIDevTools/swagger-parser#47]
I have a master swagger.yaml, which looks like

```
...
definitions:
  core.object:
    $ref: "./definitions/core/object.yaml#/definitions/core.object"
...
```

My `./definitions/core/object.yaml` looks like:

```
swagger: "2.0"
definitions:
  core.object:
    type: object
    properties:
      id:
        type: integer
      type:
        type: string
    required:
      - id
      - type
    discriminator: type
```

When `bundle()` method produces the following output for me (does not resolve `/definitions/core.object` part of the reference):

```
definitions: 
  core.object: 
    swagger:     2.0
    definitions: 
      core.object: 
        type:          object
        properties: 
          id: 
            type: integer
          type: 
            type: string
        required: 
          - id
          - type
        discriminator: type
```

Interesting, but `dereference()` produces correct output for me:

```
definitions: 
  core.object: 
    type:          object
    properties: 
      id: 
        type: integer
      type: 
        type: string
    required: 
      - id
      - type
    discriminator: type
```

I also tried `require('json-schema-ref-parser').bundle(...)` and it also produces correct output. So looks like the issue is specifically with `require('swagger-parser').bundle()` method...
